### ISSUE TITLE
calico-vpp-node pods crashlooping on cluster built with GCP VMs

### ISSUE THREAD

**Issue by lwr20** [projectcalico/vpp-dataplane#151]
**Environment**
- Calico/VPP version: prerelease
- Kubernetes version: 1.21 (also 1.20)
- Deployment type: cloud - GCP, ubuntu 18.04 LTS, e2-standard-2 VMs.  kubeadm to setup k8s.
- Network configuration: Calico / host-local IPAM? IPIP / VXLAN enabled? Specific BGP settings?

**Issue description**
calico-vpp-node pods crashlooping.

**To Reproduce**
- setup VMs, run kubeadm init on the master, kubeadm join on the nodes
- download https://gist.githubusercontent.com/lwr20/9bce7591be262bb1ed8c3f7c716d0f9a/raw/4809db96a3593767aef8c2955dc42005da59f7a3/calico-vpp-nohuge.yaml
- edit the above to set `vpp_dataplane_interface: ens4`
- kubectl apply it.

**Expected behavior**
Expected calico-vpp-node pods to not crash :) 

**Additional context**
My kubeadm config:
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:

bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: <redacted>
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  certSANs:
  - 35.192.218.118
  - 127.0.0.1
  extraArgs:
    audit-log-path: /var/log/calico/audit/kube-audit.log
    audit-policy-file: /etc/kubernetes/pki/audit-policy.yaml
  extraVolumes:
  - hostPath: /var/log/calico/audit/
    mountPath: /var/log/calico/audit/
    name: calico-audit
    pathType: DirectoryOrCreate

  timeoutForControlPlane: 4m0s
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager:
  extraArgs:
    port: "10252"

dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kubernetesVersion: v1.21.0
networking:
  dnsDomain: cluster.local
  podSubnet: "192.168.0.0/16"
  serviceSubnet: 10.96.0.0/12
scheduler: {}
---
kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
mode: iptables
```
