### ISSUE TITLE
support  mlx5 rdma as uplink

### ISSUE THREAD

**Issue by riversidekid-zz** [projectcalico/vpp-dataplane#183]
VPP natively support mlx rdma driver, it would be great if calico can support configuring rdma as uplink

**Comment by AloysAugustin** [comment]
Hello,
We're working on this, and it should be part of our next release 🙂 .
In the meantime, you should be able to use mlx interfaces with a manual configuration by setting `vpp_uplink_driver` to `none` in the calico-vpp-config ConfigMap and adding the following environment variables to the `vpp` container:

```
          env:
            - name: CALICOVPP_CONFIG_EXEC_TEMPLATE
              value: create interface rdma host-if __VPP_DATAPLANE_IF__
            - name: CALICOVPP_VPP_STARTUP_SLEEP
              value: "5"
```
