### ISSUE TITLE
calico-vpp-node fail to start on centos

### ISSUE THREAD

**Issue by KfreeZ** [projectcalico/vpp-dataplane#215]
hi I cannot bring up the calico-vpp on the centos server, this issue is not happening on ubuntu

the error log of VPP is like below:
```
time="2021-08-26T02:38:12Z" level=error msg="cannot add address 10.233.134.163/22 eno1 back to eno1 : file exists"
time="2021-08-26T02:38:12Z" level=error msg="cannot add address fe80::a6bf:1ff:fe3e:2043/64 back to eno1 : file exists"
time="2021-08-26T02:38:12Z" level=error msg="cannot add route {Ifindex: 2 Dst: fe80::/64 Src: <nil> Gw: <nil> Flags: [] Table: 254} back to eno1 : file exists"
time="2021-08-26T02:38:12Z" level=error msg="cannot add route {Ifindex: 2 Dst: 169.254.0.0/16 Src: <nil> Gw: <nil> Flags: [] Table: 254} back to eno1 : file exists"
time="2021-08-26T02:38:12Z" level=error msg="cannot add route {Ifindex: 2 Dst: 10.233.132.0/22 Src: 10.233.134.163 Gw: <nil> Flags: [] Table: 254} back to eno1 : file exists"
time="2021-08-26T02:38:12Z" level=error msg="cannot add route {Ifindex: 2 Dst: <nil> Src: <nil> Gw: 10.233.132.1 Flags: [] Table: 254} back to eno1 : file exists"
time="2021-08-26T02:38:12Z" level=error msg="Error pinging calico-vpp: Error reading /var/run/vpp/calico_vpp.pid: open /var/run/vpp/calico_vpp.pid: no such file or directory"
```

calico images:
```
docker.io/calico/node                 v3.20.0             5ef66b403f4f        3 weeks ago         170 MB
docker.io/calico/pod2daemon-flexvol   v3.20.0             5991877ebc11        3 weeks ago         21.7 MB
docker.io/calico/cni                  v3.20.0             4945b742b8e6        3 weeks ago         146 MB
docker.io/calicovpp/vpp               prerelease          514d81b351ce        5 weeks ago         556 MB
docker.io/calicovpp/agent             prerelease          6cfc16b62b46        5 weeks ago         172 MB
```

the server infomation is like below:
```
[root@wp24 calico-vpp]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 1.2.3.4
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  imagePullPolicy: IfNotPresent
  name: node
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: 1.22.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}
```
