### ISSUE TITLE
DNS resolving

### ISSUE THREAD

**Issue by glazychev-art** [projectcalico/vpp-dataplane#333]
**Environment**
- Calico/VPP version: v0.18.1-calicov3.21.2
- Kubernetes version: v1.21.1
- kind cluster

**Issue description**
Perhaps it is not related to vpp-dataplane directly, but I found this on Calico-VPP setup.

It seems that DNS resolving is not working properly. I created a simple [alpine](https://hub.docker.com/_/alpine) pod and want to install additional utilities. Called `apk update` but got an error. 

**To Reproduce**
1. Prepare alpine.yaml:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: alpine
spec:
  containers:
  - name: alpine
    securityContext:
      privileged: true
    image: alpine:3.15.0
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
```
2. Apply: `kubectl apply -f alpine.yaml`
3. Go to the container: `kubectl exec -it alpine sh`
4. 
```
/ # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.15/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: No such file or directory
2 errors; 14 distinct packages available
```
or
```
/ # ping dl-cdn.alpinelinux.org
ping: bad address 'dl-cdn.alpinelinux.org'
```

**Additional context**
If I run it with default CNI - it works.
If I add `nameserver 8.8.8.8` to `/etc/resolv.conf` - it works.
`ping 8.8.8.8` also always works.

Perhaps something needs to be specified in the configuration?

Thank you

**Comment by AloysAugustin** [comment]
Hi @glazychev-art , what is the status of the coredns pods?
`kubectl -n kube-system get pods`

**Comment by glazychev-art** [comment]
Hi @AloysAugustin ,

It seems that everything is working fine:
```
NAME                                       READY   STATUS    RESTARTS   AGE
calico-kube-controllers-547686d897-shvjz   1/1     Running   1          77m
calico-node-czltm                          1/1     Running   0          77m
calico-node-mv968                          1/1     Running   2          77m
coredns-74ff55c5b-hwlwg                    1/1     Running   0          79m
coredns-74ff55c5b-lgw8p                    1/1     Running   0          79m
etcd-test-master                           1/1     Running   0          79m
kube-apiserver-test-master                 1/1     Running   0          79m
kube-controller-manager-test-master        1/1     Running   0          79m
kube-proxy-2fln5                           1/1     Running   0          79m
kube-proxy-jppr2                           1/1     Running   0          77m
kube-scheduler-test-master                 1/1     Running   0          79m

```
I can reproduce it not only on `kind-cluster`, but also on bare-metal on `equinix.metal`

**Comment by onong** [comment]
@glazychev-art, could you try restarting network service?

**Comment by glazychev-art** [comment]
@onong 
Sorry, what exactly do I need to restart?

**Comment by onong** [comment]
@glazychev-art
Restart the networking service on the nodes, ie, "systemctl restart systemd-networkd" or whatever is applicable.

**Comment by glazychev-art** [comment]
@onong 
Thank you. Yes, `systemctl restart systemd-networkd` is applicable.
But unfortunately it didn't help.

**Comment by glazychev-art** [comment]
This is still a problem.
Additionally, I've run default Calico (without VPP dataplane) - `ping` and `apk update` work fine.

Configuration:
`kubectl apply -f https://projectcalico.docs.tigera.io/v3.22/manifests/tigera-operator.yaml`
`kubectl apply -f installation-default.yaml`

installation-default.yaml:
```
# This section includes base Calico installation configuration.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec: {}

---

# This section configures the Calico API server.
# For more information, see: https://projectcalico.docs.tigera.io/master/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer 
metadata: 
  name: default 
spec: {}
```
Any new ideas?
