### ISSUE TITLE
calico vpp failed to install on k8s cluster with dpdk as vpp_uplink_driver 

### ISSUE THREAD

**Issue by dylan2intel** [projectcalico/vpp-dataplane#465]
**Environment**
- Calico/VPP version: v3.24.0
- Kubernetes version: v1.24.4
- Deployment type: bare-metal...
- Network configuration: Calico without VXLAN
- OS: ubuntu22.04

**Issue description**
Follow the official [getting-started](https://projectcalico.docs.tigera.io/getting-started/kubernetes/vpp/getting-started) to install calico vpp failed to bring up on-premise k8s cluster.

How does it work if the k8s cluster node ip bound with dpdk driver by calico vpp when coredns pod is initializing and not ready?
Since coredns will reach DNS server with UDP per kernel driver.

**To Reproduce**

- Two network interfaces, one 10G for public ip, another 100G NIC for private ip
- k8s will use 100G NIC to setup cluster, which will be the node ip(kubectl get node -o wide)

- load vfio-pci kernel driver
`
echo "vfio-pci" > /etc/modules-load.d/95-vpp.conf
modprobe vfio-pci
`

- setup hugepages
`
echo "vm.nr_hugepages = 512" >> /etc/sysctl.conf
sysctl -p
sudo systemctl restart containerd.service
sudo systemctl restart kubelet.service
`
- kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/tigera-operator.yaml

- curl -o https://raw.githubusercontent.com/projectcalico/vpp-dataplane/v3.24.0/yaml/calico/installation-default.yaml
- edit installation-default.yaml, specify `cidr` with`10.244.0.0/16`
- kubectl apply -f installation-default.yaml

- curl -o calico-vpp.yaml https://raw.githubusercontent.com/projectcalico/vpp-dataplane/v3.24.0/yaml/generated/calico-vpp.yaml
- edit calico-vpp.yaml
- specify `vpp_dataplane_interface` with `dpdk`
- specify `vpp_dataplane_interface` with ip (kubectl get nodes -o wide)
- kubectl apply -f calico-vpp.yaml

**Expected behavior**
k8s cluster install successfully with calico vpp as CNI

**Additional context**

![image](https://user-images.githubusercontent.com/90298893/205255777-9484e53b-9f04-4e07-8cb6-d7dac359f17f.png)

![image](https://user-images.githubusercontent.com/90298893/205255906-3505cac2-0b88-40b3-a874-08357ab7520f.png)

![image](https://user-images.githubusercontent.com/90298893/205256049-b4c638e2-128a-4cd2-8fe5-9299272068c4.png)

![image](https://user-images.githubusercontent.com/90298893/205258579-49e28606-cd4f-4fe9-86fe-77e0623394c8.png)

![image](https://user-images.githubusercontent.com/90298893/205258685-4f1858b9-27c9-4660-9d86-9c6b5526522f.png)

**Comment by dylan2intel** [comment]
New findings for root cause addressing on coredns timeout

![image](https://user-images.githubusercontent.com/90298893/205272614-9f256405-266d-4e50-a452-9bb165e9c72f.png)

**Comment by dylan2intel** [comment]
Hey guys, 

Any workaround suggestions or fixes for this issue?

**Comment by onong** [comment]
Hi @dylan2intel, could you try it in ubuntu 20.04?

**Comment by dylan2intel** [comment]
Currently I can workaround this issue with static ip configured as below, However if dhcp enabled, it always fails. Why?

My internal network is under control of a physic switch with ip/mac address mapping.

cat /etc/netplan/00-installer-config.yaml

```
network:
  ethernets:
    ens259f0:
      addresses:
      - 172.17.29.19/23
      routes:
        - to: default
          via: 172.17.28.1
      nameservers:
        addresses:
        - 10.248.2.5
        - 172.17.6.9
        - 10.239.27.228
        search:
        - cd.intel.com
    ens259f1:
      dhcp4: true
    ens817f0:
      #dhcp4: true ############## Here if dhcp enabled, it will always fail #############
      addresses:
      - 192.168.126.4/24
    ens817f1:
      dhcp4: true
    enx2a24b96f8630:
      dhcp4: true
  version: 2
```
I think this workaround is a huge limitation, root cause still need to address.
