### ISSUE TITLE
Not able to configure the BGP AS number for Calico cluster

### ISSUE THREAD

**Issue by sknat** [projectcalico/vpp-dataplane#5]
copied from https://github.com/calico-vpp/calico-vpp/issues/7

-------------------

##########
calico/kube-controllers:v3.9.1
calicovpp/cni:v3.9.1-1
calico/pod2daemon-flexvol:v3.9.1
calicovpp/node:v3.9.1-6
calicovpp/vpp:v3.9.1-13
##########

I have a 3 nodes cluster (one master + two workers). 

I enabled BGP within the cluster using the following configuration:

```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  asNumber: 65000
```

The asNumber option is not applied. We used gobgp cli tool to verify it:

```
[root@k8s-ansible-5 ~]# ./gobgp neighbor
Peer            AS     Up/Down State       |#Received  Accepted
10.100.1.4   64512 1d 08:59:11 Establ      |        0         0
10.100.1.6   64512 1d 08:59:09 Establ      |        4         4
```

Thanks,
Laurent.
