### ISSUE TITLE
eBGP with external routers not working

### ISSUE THREAD

**Issue by sknat** [projectcalico/vpp-dataplane#6]
copied from https://github.com/calico-vpp/calico-vpp/issues/6

-------------------

##########
calico/kube-controllers:v3.9.1
calicovpp/cni:v3.9.1-1
calico/pod2daemon-flexvol:v3.9.1
calicovpp/node:v3.9.1-6
calicovpp/vpp:v3.9.1-13
##########

I have a 3 nodes cluster (one master + two workers). I want to create an eBGP session between each worker and a pair of external routers. 

Calico BGP config:

```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: bgppeer-isr4k2
spec:
  peerIP: 10.100.1.253
  node: k8s-ansible-6
  asNumber: 65100
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: bgppeer-isr4k1
spec:
  peerIP: 10.100.1.252
  node: k8s-ansible-5
  asNumber: 65100
```

The session not coming up. Below are the logs from the router side:

```
Mar 16 09:59:59.797: BGP: 10.100.1.5 active went from Idle to Active
Mar 16 09:59:59.797: BGP: 10.100.1.5 open active, local address 10.100.1.252
Mar 16 10:00:04.798: BGP: 10.100.1.5 open failed: Connection timed out; remote host not responding
```

Using the gobgp cli tool, we can validate BGP is working between the nodes but not with the external peer:

```
[root@k8s-ansible-5 ~]# ./gobgp neighbor
Peer            AS     Up/Down State       |#Received  Accepted
10.100.1.4   64512 1d 09:13:26 Establ      |        0         0
10.100.1.6   64512 1d 09:13:24 Establ      |        4         4
10.100.1.252 65100       never Active      |        0         0
```

If we switch to an iBGP session instead, it does work:

```
[root@k8s-ansible-5 ~]# ./gobgp neighbor
Peer            AS     Up/Down State       |#Received  Accepted
10.100.1.4   64512 1d 08:59:11 Establ      |        0         0
10.100.1.6   64512 1d 08:59:09 Establ      |        4         4
10.100.1.252 64512    00:02:04 Establ      |        0         0
```

Thanks,
Laurent.
